services:
    laravel:
        container_name: laravel
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./database/database.sqlite:/var/www/html/database/database.sqlite
        environment:
            - APP_ENV=production
            - APP_KEY=
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
