services:
    laravel:
        image: laravel-react-demo
        container_name: laravel
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./db:/var/www/html/db
        environment:
            - APP_ENV=production
            - APP_KEY=
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/db/database.sqlite
            - SESSION_DRIVER=file
